branches:
  only:
  - master
language: r
sudo: false
git:
  depth: false
cache: 
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_book
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
script:
  - ./_build.sh
deploy:
  provider: script
  script: ./_deploy.sh
  skip_cleanup: true
